[profile.default]
solc_version = "0.8.28"
ffi = true
remappings = [
  "forge-std/=lib/forge-std/src/",
  "solmate/=lib/solmate/src/",
  "@selfxyz/contracts/=lib/selfxyz-contracts/contracts/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]
